config/routes.rb
Rails.application.routes.draw do
  resources :blogs, path: 'posts' #, param: :title
  
  
  devise_for :users
  get 'home/index'
  root 'blogs#index'
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  validates :title,  presence: true
  validates :post,  presence: true
  validates :post_summary,  presence: true
  
  def to_param
    # change spaces in title to hyphens -
    #title.strip.gsub!(/\s/,'-')
    title.gsub!(' ', '-')
    #change URL from ID to ID-Title
    "#{title}"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blog, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :first_name, :last_name])
  end
  
  

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @fun = (params[:id]) 
      @fun.gsub!('-',' ')
      #@blog =  Blog.find_by(title: (params[:title]))
      @blog = Blog.find_by_title(@fun)
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :post, :meta_keyword, :meta_description, :post_summary, :category, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= tinymce_assets %>

<% if user_signed_in? && current_user.admin == 41 %>
  <%= form_for(@blog) do |f| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
  
        <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, size: "40x1", value: (if @blog.title then @blog.title.gsub('-',' ') end) %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :post %><br>
      <%= tinymce %>
      <%= f.text_area :post, :class => "tinymce", :rows => 40, :cols => 120 %>
    </div>
    <br/><br/>
    <div class="field">
      <%= f.label :post_summary %><br>
      <%= f.text_area :post_summary, size: "40x5" %>
    </div>
    
    
    
    <br/><br/><br/>   
    <div class="field">
      <%= f.label "Tags" %><br>
      <%= f.text_field :meta_keyword %>
    </div>
    <div class="field">
      <%= f.label :meta_description %><br>
      <%= f.text_field :meta_description %>
    </div>
   
    <div class="field">
      <%= f.label :category %><br>
      <%= f.text_field :category %>
    </div>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <br/>
    <div class="actions">
      <%= f.submit "Create Blog Post" %>
    </div>
  <% end %>

<% else %>
  Sorry, you're not authorized here...
  <br/><br/>
<% end %>

app/views/blogs/edit.html.erb
<% content_for :title, "Edit Blog" %>


<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', root_path %>

app/views/blogs/index.html.erb
<% content_for :title, "Blog Posts" %>





    <% @blogs.order("created_at desc").each do |blog| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= link_to blog.title.titleize, blog %></h3>
        </div>
        <div class="panel-body">
              
              <%= blog.post_summary %>
        </div>
          <div class="panel-footer">
            <%= link_to 'Continue Reading...', blog %>
            <% if user_signed_in? && current_user.admin == 41 %>
              (<%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>)
            <% end %> 
          </div>
      </div>
      <br/><br/>
    <% end %>
  
<br>

app/views/blogs/new.html.erb
<% content_for :title, "New Blog Post" %>

<%= render 'form' %>

<%= link_to 'Back', root_path %>
<br/><br/><br/><br/>

app/views/blogs/show.html.erb
<% content_for :title, @blog.title.titleize %>
<% content_for :tags, @blog.meta_keyword %>
<% content_for :meta_description, @blog.meta_description %>
<% @blog.post_summary %>
<% @blog.category %>

<% Blog.find_by(title: @blog.title).inspect %>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @blog.title.titleize %></h3>
  </div>
  <div class="panel-body">
    
    <p>
      By:
      <%= User.find(@blog.user_id).first_name.titleize %> 
      <%= User.find(@blog.user_id).last_name.titleize %>
    </p>
    <br/>
    <p>
      <%= @blog.post.html_safe %>
    </p>
    
    
    </div>
  <div class="panel-footer">
    <%= link_to 'Back', root_path %>
    <% if user_signed_in? && current_user.admin == 41 %>
      | <%= link_to 'Edit', edit_blog_path(@blog) %> | 
      <%= link_to 'Delete Post', blog_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %> 
  </div>
</div>

app/views/home/_flash_alerts.html.erb
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

app/views/home/_footer.html.erb
</div>

<footer class="short" id="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-8">
							<h4>About John <strong>Elder</strong></h4>
							<p align="justify">John is a Web Developer, Internet Marketer, Author, and Entrepreneur with over <%= Time.now.year - 1997 %> years experience building and running successful tech startups, with several successful exits under his belt.  Today he's building Codemy.com to teach people to code online using a blend of instructional videos and hands on help... <br/><a href="http://www.JohnElder.org" class="btn-flat btn-xs">View More <i class="fa fa-arrow-right"></i></a></p>
							<hr class="light">
						</div>
						<div class="col-md-3 col-md-offset-1">
							
							
							<div class="social-icons">
								<ul class="social-icons">
									<li class="facebook"><a href="http://www.facebook.com/codemycom" target="_blank" data-placement="bottom" data-tooltip title="Facebook">Facebook</a></li>
									<li class="twitter"><a href="https://twitter.com/flatplanet" target="_blank" data-placement="bottom" data-tooltip title="Twitter">Twitter</a></li>
									<li class="linkedin"><a href="http://www.linkedin.com/pub/john-elder/55/a31/493" target="_blank" data-placement="bottom" data-tooltip title="Linkedin">Linkedin</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container">
						<div class="row">
							
							<div class="col-md-12">
								<p>Copyright &copy; John Elder - All Rights Reserved</p>
							</div>
						</div>
					</div>
				</div>
			</footer>
	
		</div>

		<!-- Vendor -->
		<script src="https://cdn.johnelder.org/vendor/jquery/jquery.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.appear/jquery.appear.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.easing/jquery.easing.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery-cookie/jquery-cookie.js"></script>
		<script src="http://cdn.johnelder.org/vendor/bootstrap/bootstrap.js"></script>
		<script src="http://cdn.johnelder.org/vendor/common/common.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.validation/jquery.validation.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.stellar/jquery.stellar.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jquery.gmap/jquery.gmap.js"></script>
		<script src="http://cdn.johnelder.org/vendor/isotope/jquery.isotope.js"></script>
		<script src="http://cdn.johnelder.org/vendor/owlcarousel/owl.carousel.js"></script>
		<script src="http://cdn.johnelder.org/vendor/jflickrfeed/jflickrfeed.js"></script>
		<script src="http://cdn.johnelder.org/vendor/magnific-popup/jquery.magnific-popup.js"></script>
		<script src="http://cdn.johnelder.org/vendor/vide/vide.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="http://cdn.johnelder.org/js/theme.js"></script>
		
		
		<!-- Theme Custom -->
		<script src="http://cdn.johnelder.org/js/custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="http://cdn.johnelder.org/js/theme.init.js"></script>


		

app/views/home/_header.html.erb
<div class="body">
			<header id="header" class="narrow" data-plugin-options='{"alwaysStickyEnabled": false, "stickyEnabled": false, "stickyWithGap": false, "stickyChangeLogoSize": false}'>
				<div class="container">
					<div class="logo">
						<a href="index.php">
							<h2 class="shorter"><a href="http://www.JohnElder.org" class="nolink">John<strong>Elder</strong>.org</a></h2>
							
						</a>
					</div>
					<button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
						<i class="fa fa-bars"></i>
					</button>
				</div>
				<div class="navbar-collapse nav-main-collapse collapse">
					<div class="container">
						<ul class="social-icons">
							<li class="facebook"><a href="http://www.facebook.com/codemycom" target="_blank" title="Facebook">Facebook</a></li>
							<li class="twitter"><a href="https://twitter.com/flatplanet" target="_blank" title="Twitter">Twitter</a></li>
							<li class="linkedin"><a href="http://www.linkedin.com/pub/john-elder/55/a31/493" target="_blank" title="Linkedin">Linkedin</a></li>
						</ul>
						<nav class="nav-main mega-menu">
							<ul class="nav nav-pills nav-main" id="mainMenu">
								
															
							

								
								<li>
									<% if user_signed_in? %>
									<li class="dropdown">
									<a class="dropdown-toggle" href="#">
										Blog
										<i class="fa fa-angle-down"></i>
									</a>
										<ul class="dropdown-menu">
											<li><%= link_to "Blog Home", root_path %></li>
	                                        <li><%= link_to "New Post", new_blog_path %></li>
	                                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	                                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	                                    </ul>
	                                </li>
									<% else %>
										<%= link_to "Login", new_user_session_path %>
									<% end %>
								</li>
							
								<li>
									<a href="http://JohnElder.org/portfolio.php">Portfolio</a>
								</li>
							
								<li>
									<a href="http://JohnElder.org/testimonials.php">Testimonials</a>
								</li>

								<li>
									<a href="http://cdn.JohnElder.org/resume.pdf">Resume</a>
								</li>
								
								<li>
									<a href="http://JohnElder.org/index.php#contact">Contact</a>
								</li>

								<li>
									<a href="http://JohnElder.org/code/index.php">Code</a>
								</li>
								
							</ul>
						</nav>
					</div>
				</div>
			</header>
			
			

				<section class="page-top">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><%= link_to "Home", root_path %></li>
									<li class="active"><%= yield(:title) %></li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1><%= yield(:title) %></h1>
							</div>
						</div>
					</div>
				</section>

<div class="container">



<br/>

app/views/home/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JohnElder.org >> Blog", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_blog_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_porto_css.html.erb
        <!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="http://cdn.johnelder.org/vendor/bootstrap/bootstrap.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/vendor/fontawesome/css/font-awesome.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/vendor/owlcarousel/owl.carousel.min.css" media="screen">
		<link rel="stylesheet" href="http://cdn.johnelder.org/vendor/owlcarousel/owl.theme.default.min.css" media="screen">
		<link rel="stylesheet" href="http://cdn.johnelder.org/vendor/magnific-popup/magnific-popup.css" media="screen">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/theme.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/theme-elements.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/theme-blog.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/theme-shop.css">
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/theme-animate.css">

		<!-- Skin CSS -->
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/skins/default.css">

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="http://cdn.johnelder.org/css/custom2.css">

		<!-- Head Libs -->
		<script src="http://cdn.johnelder.org/vendor/modernizr/modernizr.js"></script>

		<!--[if IE]>
			<link rel="stylesheet" href="css/ie.css">
		<![endif]-->

		<!--[if lte IE 8]>
			<script src="vendor/respond/respond.js"></script>
			<script src="vendor/excanvas/excanvas.js"></script>
		<![endif]-->

app/views/home/index.html.erb
Welcome to my blog!
<br/>
it's gonna be huge...

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | JohnElder.org</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <% if yield(:meta_description) != "" %>
    <meta name="description" content="<%= yield(:meta_description) %>">
  <% end %>
    
  <%= render 'home/porto_css' %>

</head>
<body>
<%= render "home/header" %>
<% render "home/nav" %>

<div class="container">
  <%= render "home/flash_alerts" %>
  <%= yield %>
</div>

<%= render 'home/footer' %>
</body>
</html>